### ISSUE TITLE
Have the example python script use localtime() function

### ISSUE THREAD

**Issue by rclagett** [Netuitive/netuitive-client-python#14]
In Python 2.7.10 and 2.7.13, versions shipped with Mac OSX, the gmtime() function of the time module is 5 hours ahead of actual time. This creates data with timestamps in the future to which the the platforms drops. I am proposing we use the localtime() function which is on par with current GMT time in the aforementioned versions of Python and the version used by the Dockerfile

**Comment by tombakerjr** [comment]
@rclagett should this issue be closed?

**Comment by rclagett** [comment]
@tombakerjr yes, it was addressed by https://github.com/Netuitive/netuitive-client-python/pull/15
